[project]
name = "final-project-ironhack-da"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pdfplumber>=0.11.5",
    "plotly-express>=0.4.1",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]
